import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import "./globals.css";
import AuthSession from './_components/AuthSession';
import Header from './_components/Header';
import { auth } from '@/auth';

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "캐치마인드",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body className={cn(fontSans.variable)}>
        <AuthSession>
          <div className='min-h-dvh flex flex-col'>
            <Header session={session} />
            <div className='flex flex-grow'>
              {children}
            </div>
          </div>
        </AuthSession>
      </body>
    </html>
  );
}
